# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(367, 320)
        self.btn_send = QtWidgets.QPushButton(Form)
        self.btn_send.setGeometry(QtCore.QRect(140, 20, 89, 25))
        self.btn_send.setObjectName("btn_send")
        self.lineedit_input_tic = QtWidgets.QLineEdit(Form)
        self.lineedit_input_tic.setGeometry(QtCore.QRect(20, 20, 113, 25))
        self.lineedit_input_tic.setObjectName("lineedit_input_tic")
        self.textbrowser_show = QtWidgets.QTextBrowser(Form)
        self.textbrowser_show.setGeometry(QtCore.QRect(20, 70, 256, 192))
        self.textbrowser_show.setObjectName("textbrowser_show")
        self.btn_stop = QtWidgets.QPushButton(Form)
        self.btn_stop.setGeometry(QtCore.QRect(240, 20, 89, 25))
        self.btn_stop.setObjectName("btn_stop")

        self.retranslateUi(Form)
        self.btn_send.clicked.connect(Form.send) # type: ignore
        self.btn_stop.clicked.connect(Form.stop) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_send.setText(_translate("Form", "send"))
        self.btn_stop.setText(_translate("Form", "stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
